version: "3"

services:

  borg:
    container_name: borg
    build: .
    ports:
      # Must match [host] and [port] env variables
      # except you know what you're doing ...
      - 192.168.5.23:22222:22
    volumes:
      # expects private key file for [remote_user] on [remote_host]
      - ./private.key:/key/private.key
      # The repo; as long as the password is the same, 
      # this can overlap with other containers
      - ./repo:/repo
      # borg executables will be downloaded on every recreation of the container
      # this denies it ...
      - ./borg:/borg
    environment:
      - mysql_db_containers="wordpress_1 wordpress_2"
      - postgres_db_containers=
      - mongo_db_containers=example_mongo_db_1
      - backup_paths="/etc /data"
      - INTERVAL=86400
      - host=accessable.docker.host
      - port=22222
      - BORG_PASSPHRASE=verylongandsecure
      - remote_user=borg
      - remote_host=location.to.backup
      - remote_port=22
